name: Lint and check formatting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_nix_targets:
    name: Build Nix targets
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v3
      - name: Activate Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-flakehub: false

      - name: Test formatting
        run: |
          nix develop --impure -c devenv test
